[substrate]
name = "spheres_500_gamma_shape2_scale1p5_gap1"
periodic = false
position = "uniform"

[simulation]
n_walkers = 100000
n_t = 10000
diffusivity = 1e-9
seed = 123

[waveform]
waveform_file = ["LTE0hz.csv", "LTE50hz.csv", "LTE100hz.csv", "STEiso.csv", "STEaniso.csv"]
rotation_file = ["fibRot40.txt", "fibRot40.txt", "fibRot40.txt", "ESRD2_0040.txt", "ESRD2_0040.txt"]
b_targets = [0, 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]

# Optional. 0.02 ms (20 us) if omitted.
# raster_time_ms = 0.02

# Optional. Unit conversion applied to raw waveform values to get T/m. Defaults to 1e-3
# gradient_scale = 1e-3

[trajectory]
enabled = false
n_walkers = 10
